### ISSUE TITLE
Compatibility risk: resolvedOptions().hour12 is removed

### ISSUE THREAD

**Issue by littledan** [zbraniecki/proposal-ecma402-hourcycle#1]
In [resolvedOptions()](https://rawgit.com/zbraniecki/proposal-ecma402-hourcycle/master/out/#sec-intl.datetimeformat.prototype.resolvedoptions), the specification remains to create a property for each internal slot. However, as the `[[hour12]]` internal slot is removed, this proposed specification seems to remove that property. This property may be used in existing web applications.

To address the issue, I'd suggest creating an `hour12` property *if* the `[[hourCycle]]` property contains one of the two values previously supported.

**Comment by zbraniecki** [comment]
Fixed by https://github.com/zbraniecki/proposal-ecma402-hourcycle/commit/c2cb563ec7f380837b434eb4eea80eec139cfbe5
